// our application state is generated by reducer functions, as such:
export default function () {
  return [
    {title: 'Javascript: The Good Parts', pages: 101},
    {title: 'Harry Potter', pages: 200},
    {title: 'The Dark Tower', pages: 50},
    {title: 'Eloquent Ruby', pages: 1}
  ]
}
